name: Build C++ Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Discover Working Directory
      id: setdir
      run: |
        if (Test-Path "CombatMaster_Assistant\CMakeLists.txt") {
            echo "workdir=CombatMaster_Assistant" >> $env:GITHUB_ENV
        } elseif (Test-Path "combatMaster_assistant\CMakeLists.txt") {
            echo "workdir=combatMaster_assistant" >> $env:GITHUB_ENV
        } else {
            echo "workdir=." >> $env:GITHUB_ENV
        }

    - name: Download imgui
      working-directory: ${{ env.workdir }}
      run: |
        git clone -b docking https://github.com/ocornut/imgui.git include/imgui
      
    - name: Download nlohmann json
      working-directory: ${{ env.workdir }}
      run: |
        mkdir include\nlohmann
        curl -L https://github.com/nlohmann/json/releases/download/v3.11.3/json.hpp -o include/nlohmann/json.hpp
        
    - name: Configure CMake
      working-directory: ${{ env.workdir }}
      run: cmake -B build -A x64

    - name: Build
      working-directory: ${{ env.workdir }}
      run: cmake --build build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: CombatMaster_Assistant
        path: |
          ${{ env.workdir }}/build/Release/CombatMaster_Assistant.exe
          ${{ env.workdir }}/build/Release/resources/config.json
