name: Build Internal DLL

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Discover Working Directory
      id: setdir
      run: |
        if (Test-Path "CombatMaster_Assistant\CMakeLists.txt") {
            echo "workdir=CombatMaster_Assistant" >> $env:GITHUB_ENV
        } elseif (Test-Path "combatMaster_assistant\CMakeLists.txt") {
            echo "workdir=combatMaster_assistant" >> $env:GITHUB_ENV
        } else {
            echo "workdir=." >> $env:GITHUB_ENV
        }

    - name: Download imgui
      working-directory: ${{ env.workdir }}
      run: |
        Remove-Item -Recurse -Force include/imgui -ErrorAction Ignore
        git clone -b docking https://github.com/ocornut/imgui.git include/imgui

    - name: Configure CMake
      working-directory: ${{ env.workdir }}
      run: cmake -B build -A x64

    - name: Build
      working-directory: ${{ env.workdir }}
      run: cmake --build build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Nexus_Internal_DLL
        path: |
          ${{ env.workdir }}/build/Release/Nexus_Internal.dll
